config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#home'
  resources :users
  resources :raps, only: [:index, :new, :create, :show, :update, :edit, :destroy]
  resources :beats, only: [:index, :new, :create, :show, :update, :edit, :destroy]
  resources :compositions, only: [:index, :new, :create, :show, :update, :edit, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beat.rb
class Beat < ApplicationRecord
  validates :url, presence: true

end

app/models/composition.rb
class Composition < ApplicationRecord
  validates :url, presence: true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/rap.rb
class Rap < ApplicationRecord
  validates :url, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/beats_controller.rb
class BeatsController < ApplicationController
   before_action :authenticate_user!,except:[:index]
  def index
   @beats = Beat.all
  end
  def new
    @beat = Beat.new # needed to instantiate the form_for

  end

  def create
    @beat = Beat.new(beat_params)
    @beat.save
    redirect_to beats_path(@beat)
    # Will raise ActiveModel::ForbiddenAttributesError
  end

  def edit
    @beat = Beat.find(params[:id])
  end

  def update
    @beat = Beat.find(params[:id])
    @beat.update(beat_params)
    # no need for app/views/restaurants/update.html.erb
    redirect_to beats_path(@beat)
  end

  def destroy
    @beat = Beat.find(params[:id])
    @beat.destroy
    redirect_to beats_path
  end

  private

  def beat_params
    params.require(:beat).permit(:url)
  end

end

app/controllers/compositions_controller.rb
class CompositionsController < ApplicationController
  before_action :authenticate_user!,except:[:index]
  def index
   @compositions = Composition.all
  end
  def new
    @composition = Composition.new # needed to instantiate the form_for

  end

  def create
    @composition = Composition.new(composition_params)
    @composition.save
    redirect_to compositions_path(@composition)
    # Will raise ActiveModel::ForbiddenAttributesError
  end

  def edit
    @composition = Composition.find(params[:id])
  end

  def update
    @composition = Composition.find(params[:id])
    @composition.update(composition_params)
    # no need for app/views/restaurants/update.html.erb
    redirect_to compositions_path(@composition)
  end

  def destroy
    @composition = Composition.find(params[:id])
    @composition.destroy
    redirect_to compositions_path
  end

  private

  def composition_params
    params.require(:composition).permit(:url)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
  def beat
  end
  def composition
  end
  def rap
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/controllers/raps_controller.rb
class RapsController < ApplicationController
   before_action :authenticate_user!,except:[:index]
  def index
   @raps = Rap.all
  end
  def new
    @rap = Rap.new # needed to instantiate the form_for

  end

  def create
    @rap = Rap.new(rap_params)
    @rap.save
    redirect_to raps_path(@rap)
    # Will raise ActiveModel::ForbiddenAttributesError
  end

  def edit
    @rap = Rap.find(params[:id])
  end

  def update
    @rap = Rap.find(params[:id])
    @rap.update(rap_params)
    # no need for app/views/restaurants/update.html.erb
    redirect_to raps_path(@rap)
  end

  def destroy
    @rap = Rap.find(params[:id])
    @rap.destroy
    redirect_to raps_path
  end

  private

  def rap_params
    params.require(:rap).permit(:url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beats_helper.rb
module BeatsHelper
end

app/helpers/compositions_helper.rb
module CompositionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/raps_helper.rb
module RapsHelper
end

app/views/beats/edit.html.erb
  <%= simple_form_for [ @beat ] do |f| %>
    <%= f.input :url %>
    <%= f.submit "Save changes", class: "btn btn-primary" %>
  <% end %>

app/views/beats/index.html.erb
<%= render "components/menu" %>
<!--Carousel Wrapper-->
<div class="img-back"><%= link_to(image_tag("button.png", alt: "Gust - all rights reserved."), root_path) %></div>
<div id="carousel-example-1z" class="carousel slide carousel-fade carousel-bottom" data-ride="carousel">
  <!--Indicators-->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-1z" data-slide-to="1"></li>
    <li data-target="#carousel-example-1z" data-slide-to="2"></li>
  </ol>
  <!--/.Indicators-->
  <!--Slides-->
  <div class="carousel-inner" role="listbox">
    <!--First slide-->
    <div class="carousel-item active">
      <img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(130).jpg"
        alt="First slide">
    </div>
    <!--/First slide-->
    <!--Second slide-->
    <div class="carousel-item">
      <img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(129).jpg"
        alt="Second slide">
    </div>
    <!--/Second slide-->
    <!--Third slide-->
    <div class="carousel-item">
      <img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(70).jpg"
        alt="Third slide">
    </div>
    <!--/Third slide-->
  </div>
  <!--/.Slides-->
  <!--Controls-->
  <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  </div>
</div>


  <% if user_signed_in? %>
    <div class="ajouter-btn"><%= link_to "Ajouter", new_beat_path %></div>
  <% end %>

<!--/.Carousel Wrapper-->


<div>
  <div class="video-mobile video-ipad video-medium video-desktop">
      <% @beats.each do |beat| %>
      <div class ="card-video">
        <div class ="card-item">
          <% if user_signed_in? %>
          <%= link_to 'Supprimer', beat_path(beat),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
          <%= link_to "Editer", edit_beat_path(beat.id)%>
          <% end %>
        </div>
          <div class="margin-video" >
            <iframe width="320" height="240"
              src= <%= beat.url %>
              frameborder="0"
              allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen>
            </iframe>
          </div>
      </div>
      <% end %>
    </div>
</div>

<%= render "components/footer" %>

app/views/beats/new.html.erb
<div class="d-flex container justify-content-center display-bubble">
   <h3 class="title-new">Ajouter un Beat</h3>


    <%= simple_form_for(@beat) do |f| %>
         <%= f.error_notification %>
         <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

         <div class="form-inputs">
           <%= f.input :url %>

         </div>

         <div class="form-actions">
           <%= f.button :submit, class: "btn btn-danger title-new" %>
         </div>
       <% end %>
</div>

app/views/compositions/edit.html.erb
  <%= simple_form_for [ @composition ] do |f| %>
    <%= f.input :url %>
    <%= f.submit "Save changes", class: "btn btn-primary" %>
  <% end %>

app/views/compositions/index.html.erb
<%= render "components/menu" %>
<!--Carousel Wrapper-->
<div class="img-back"><%= link_to(image_tag("button.png", alt: "Gust - all rights reserved."), root_path) %></div>
<div id="carousel-example-1z" class="carousel slide carousel-fade carousel-bottom" data-ride="carousel">
  <!--Indicators-->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-1z" data-slide-to="1"></li>
    <li data-target="#carousel-example-1z" data-slide-to="2"></li>
  </ol>
  <!--/.Indicators-->
  <!--Slides-->
  <div class="carousel-inner" role="listbox">
    <!--First slide-->
    <div class="carousel-item active">
      <img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(130).jpg"
        alt="First slide">
    </div>
    <!--/First slide-->
    <!--Second slide-->
    <div class="carousel-item">
      <img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(129).jpg"
        alt="Second slide">
    </div>
    <!--/Second slide-->
    <!--Third slide-->
    <div class="carousel-item">
      <img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(70).jpg"
        alt="Third slide">
    </div>
    <!--/Third slide-->
  </div>
  <!--/.Slides-->
  <!--Controls-->
  <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <!--/.Controls-->
</div>
<% if user_signed_in? %>
<div class="ajouter-btn"><%= link_to "Ajouter", new_composition_path %></div>
<% end %>
<!--/.Carousel Wrapper-->
</div>

<div>
<div class="video-mobile video-ipad video-medium video-desktop">
    <% @compositions.each do |composition| %>
    <div class="space"></div>
    <div class ="card-video">
      <div class ="card-item">
        <% if user_signed_in? %>
        <%= link_to 'Supprimer', composition_path(composition),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
        <%= link_to "Editer", edit_composition_path(composition.id)%>
        <% end %>
      </div>
      <div class="margin-video" >
      <iframe width="320" height="240"
        src= <%= composition.url %>
        frameborder="0"
        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen>
      </iframe>
      </div>
    </div>
    <% end %>
  </div>
</div>

<%= render "components/footer" %>

app/views/compositions/new.html.erb
<div class="d-flex container justify-content-center display-bubble">
   <h3 class="title-new">Ajouter une composition</h3>


    <%= simple_form_for(@composition) do |f| %>
         <%= f.error_notification %>
         <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

         <div class="form-inputs">
           <%= f.input :url %>

         </div>

         <div class="form-actions">
           <%= f.button :submit, class: "btn btn-danger title-new" %>
         </div>
       <% end %>
</div>

app/views/home/home.html.erb
<%= render "components/menu" %>
<!--Carousel Wrapper-->
<div id="carousel-example-1z" class="carousel slide carousel-fade carousel-bottom" data-ride="carousel">
  <!--Indicators-->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-1z" data-slide-to="1"></li>
    <li data-target="#carousel-example-1z" data-slide-to="2"></li>
  </ol>
  <!--/.Indicators-->
  <!--Slides-->
  <div class="carousel-inner" role="listbox">
    <!--First slide-->
    <div class="carousel-item active">
      <img class="d-block w-100 carousel-resp" src="https://mdbootstrap.com/img/Photos/Slides/img%20(130).jpg"
        alt="First slide">
    </div>
    <!--/First slide-->
    <!--Second slide-->
    <div class="carousel-item">
      <img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(129).jpg"
        alt="Second slide">
    </div>
    <!--/Second slide-->
    <!--Third slide-->
    <div class="carousel-item">
      <img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(70).jpg"
        alt="Third slide">
    </div>
    <!--/Third slide-->
  </div>
  <!--/.Slides-->
  <!--Controls-->
  <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <!--/.Controls-->

</div>
<div>
<div class="mosaic" >
  <div class="card-image">
    <h1 class="bottom-left">RAP</h1>
    <div class="img-home"><%= link_to(image_tag("card.jpg", alt: "Gust - all rights reserved."), raps_path) %>
  </div>
  </div>
   <div class="card-image">
    <h1 class="bottom-left">COMPOSITION</h1>
    <div class="img-home"><%= link_to(image_tag("card2.jpg", alt: "Gust - all rights reserved."), compositions_path) %></div>
  </div>
  <div class="card-image">
    <h1 class="bottom-left">BEATS</h1>
    <div class="img-home"><%= link_to(image_tag("card.jpg", alt: "Gust - all rights reserved."), beats_path) %></div>
  </div>

</div>
<%= render "components/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gustmusic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
   <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/raps/edit.html.erb
 <%= simple_form_for [ @rap ] do |f| %>
    <%= f.input :url %>
    <%= f.submit "Save changes", class: "btn btn-primary" %>
  <% end %>

app/views/raps/index.html.erb
<%= render "components/menu" %>
<!--Carousel Wrapper-->
<div class="img-back"><%= link_to(image_tag("button.png", alt: "Gust - all rights reserved."), root_path) %></div>
<div id="carousel-example-1z" class="carousel slide carousel-fade carousel-bottom" data-ride="carousel">
  <!--Indicators-->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-1z" data-slide-to="1"></li>
    <li data-target="#carousel-example-1z" data-slide-to="2"></li>
  </ol>
  <!--/.Indicators-->
  <!--Slides-->
  <div class="carousel-inner" role="listbox">
    <!--First slide-->
    <div class="carousel-item active">
      <img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(130).jpg"
        alt="First slide">
    </div>
    <!--/First slide-->
    <!--Second slide-->
    <div class="carousel-item">
      <img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(129).jpg"
        alt="Second slide">
    </div>
    <!--/Second slide-->
    <!--Third slide-->
    <div class="carousel-item">
      <img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(70).jpg"
        alt="Third slide">
    </div>
    <!--/Third slide-->
  </div>
  <!--/.Slides-->
  <!--Controls-->
  <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <!--/.Controls-->
</div>
</div>

<% if user_signed_in? %>
 <div class="ajouter-btn"><%= link_to "Ajouter", new_rap_path %></div>
<% end %>



<div>
<div class="video-mobile video-ipad video-medium video-desktop">
    <% @raps.each do |rap| %>
    <div class ="card-video">
      <div class ="card-item">
        <% if user_signed_in? %>
        <%= link_to 'Supprimer', rap_path(rap),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
        <%= link_to "Editer", edit_rap_path(rap.id)%>
        <% end %>
      </div>
      <div class="margin-video" >
      <iframe width="320" height="240"
        src= <%= rap.url %>
        frameborder="0"
        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen>
      </iframe>
      </div>
    </div>
    <% end %>
  </div>
</div>

<%= render "components/footer" %>

app/views/raps/new.html.erb
<div class="d-flex container justify-content-center display-bubble">
   <h3 class="title-new">Ajouter une vidéo de Rap</h3>


    <%= simple_form_for(@rap) do |f| %>
         <%= f.error_notification %>
         <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

         <div class="form-inputs">
           <%= f.input :url %>

         </div>

         <div class="form-actions">
           <%= f.button :submit, class: "btn btn-danger title-new" %>
         </div>
       <% end %>
</div>